### ISSUE TITLE
Custom Serializers

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trio-run-in-process#7]
## What was wrong?

The pickle/unpickle is a performance bottleneck that isn't necessary for simple payloads.

## How can it be fixed?

Extend the API to allow custom serializers for payloads sent to/from a child process.

**Comment by gsalgado** [comment]
I ran some benchmarks to try and find where the bottlenecks are. Here are some numbers I got by running 1k calls to `run()`, using a no-op function and a single worker process.

## pickling fn/args every run() call (standard behavior) 

 - 1KB arg: 2.93s
 - 1MB arg: 4.62s


## pickling fn/args only once, but re-sending over pipe every run() call (https://github.com/gsalgado/trio-run-in-process/commit/475445908f1b40b29446d76854b77f82bafcb9c5)

This means we just skip the pickling of fn/args, so the time difference (from above) should be the pickling overhead

 - 1KB arg: 2.52s
 - 1MB arg: 3.58s


## hard-coded fn/args in child, never passed over pipe (https://github.com/gsalgado/trio-run-in-process/commit/9fd45163a255837aa17a8df172c34dd3f0a61008)

Here the difference (from above) is the overhead of passing the data over the pipe

 - 1KB arg: 1.36s
 - 1MB arg: 1.78s

https://gist.github.com/gsalgado/8631145aa42a95ba44a645796e444b46 is the script I used to get these numbers.

And here are some numbers for pickling (1k times) different types of objects. It's interesting to notice that pickling a no-op instance method takes twice as long as pickling a 1MB bytestring. (https://gist.github.com/gsalgado/4a12e1b178232f74d1d1417bcfeedbf7)

```
Pickling instance method: 0.07781410217285156 seconds
Pickling keccak(): 0.005815982818603516 seconds
Pickling 256 bytes of data: 0.0022199153900146484 seconds
Pickling 1MB of data: 0.0367732048034668 seconds
```

So, since the pickling overhead is on the order of 0.4s for 1k calls passing an instance method and 1KB of data (or 0.6s for 1MB of data), ISTM that is not a bottleneck as in any real-world use-cases the function will not be a no-op and thus would make 0.4s an insignificant amount of time. And although the overhead of passing data over the pipe is relatively higher, I don't think it'd be significant in real-world use cases either

**Comment by pipermerriam** [comment]
So the conclusion here if I'm reading your analysis correctly is that the serialization accounts for a trivial percentage of the total execution time and thus, custom (more efficient) serialization isn't going to bag us any real performance gains.  :+1:

**Comment by gsalgado** [comment]
For the fn/args combinations I tested (and I also did it for a nontrivial instance method from a trinity component), yes. There might be fn/args that are really slow to pickle, but I say we worry about that whenever we run into one of those cases
